allowBuilds:
  better-sqlite3: true
  electron: true
  esbuild: true
  extract-file-icon: true
  node-window-manager: true
  tesseract.js: true
onlyBuiltDependencies:
  - better-sqlite3
  - electron
  - esbuild
  - extract-file-icon
  - node-window-manager
  - tesseract.js
